package CustomContent.Pack;

import com.google.gson.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.Base64;

/**
 * Parser konwertujący modele Blockbench (.bbmodel) do formatu Minecraft Java (.json)
 * oraz wypakowujący zagnieżdżone tekstury PNG z Base64.
 */
public class BbmodelParser {

    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    public static class ConversionResult {
        public String modelJson;
        public byte[] textureBytes;
        public String textureName;

        public ConversionResult(String modelJson, byte[] textureBytes, String textureName) {
            this.modelJson = modelJson;
            this.textureBytes = textureBytes;
            this.textureName = textureName;
        }
    }

    /**
     * Konwertuje plik .bbmodel do formatu modelu Minecraft JSON oraz ekstrahuje główną teksturę PNG.
     */
    public static ConversionResult convertBbmodel(File bbmodelFile, String textureNamespacePath) throws Exception {
        try (Reader reader = new InputStreamReader(new FileInputStream(bbmodelFile), StandardCharsets.UTF_8)) {
            JsonObject root = JsonParser.parseReader(reader).getAsJsonObject();

            byte[] extractedTexture = null;
            String textureFileName = bbmodelFile.getName().replace(".bbmodel", ".png");

            // 1. Ekstrakcja tekstur
            if (root.has("textures") && root.get("textures").isJsonArray()) {
                JsonArray textures = root.getAsJsonArray("textures");
                if (textures.size() > 0) {
                    JsonObject firstTex = textures.get(0).getAsJsonObject();
                    if (firstTex.has("name")) {
                        textureFileName = firstTex.get("name").getAsString();
                        if (!textureFileName.endsWith(".png")) {
                            textureFileName += ".png";
                        }
                    }
                    if (firstTex.has("source") && !firstTex.get("source").isJsonNull()) {
                        String source = firstTex.get("source").getAsString();
                        if (source.contains("base64,")) {
                            String base64 = source.substring(source.indexOf("base64,") + 7);
                            extractedTexture = Base64.getDecoder().decode(base64);
                        }
                    }
                }
            }

            // 2. Budowa wynikowego modelu Minecraft JSON
            JsonObject mcModel = new JsonObject();
            mcModel.addProperty("credit", "Generated by AmonPack Model Engine");

            // Textures dictionary
            JsonObject texturesObj = new JsonObject();
            String texKey = textureNamespacePath;
            if (texKey.endsWith(".png")) {
                texKey = texKey.substring(0, texKey.length() - 4);
            }
            texturesObj.addProperty("0", texKey);
            texturesObj.addProperty("1", texKey);
            texturesObj.addProperty("2", texKey);
            texturesObj.addProperty("particle", texKey);
            mcModel.add("textures", texturesObj);

            // Elements
            if (root.has("elements") && root.get("elements").isJsonArray()) {
                JsonArray srcElements = root.getAsJsonArray("elements");
                JsonArray outElements = new JsonArray();

                for (JsonElement el : srcElements) {
                    if (!el.isJsonObject()) continue;
                    JsonObject srcObj = el.getAsJsonObject();

                    JsonObject outObj = new JsonObject();
                    if (srcObj.has("name")) outObj.addProperty("name", srcObj.get("name").getAsString());
                    if (srcObj.has("from")) outObj.add("from", srcObj.get("from"));
                    if (srcObj.has("to")) outObj.add("to", srcObj.get("to"));

                    // Rotation
                    if (srcObj.has("rotation") || srcObj.has("origin")) {
                        JsonObject rotObj = new JsonObject();
                        if (srcObj.has("origin")) rotObj.add("origin", srcObj.get("origin"));
                        if (srcObj.has("rotation") && srcObj.get("rotation").isJsonArray()) {
                            JsonArray rot = srcObj.getAsJsonArray("rotation");
                            if (rot.size() >= 3) {
                                double rx = rot.get(0).getAsDouble();
                                double ry = rot.get(1).getAsDouble();
                                double rz = rot.get(2).getAsDouble();
                                if (rx != 0) {
                                    rotObj.addProperty("axis", "x");
                                    rotObj.addProperty("angle", rx);
                                } else if (ry != 0) {
                                    rotObj.addProperty("axis", "y");
                                    rotObj.addProperty("angle", ry);
                                } else if (rz != 0) {
                                    rotObj.addProperty("axis", "z");
                                    rotObj.addProperty("angle", rz);
                                }
                            }
                        }
                        if (rotObj.has("axis")) {
                            outObj.add("rotation", rotObj);
                        }
                    }

                    // Faces
                    if (srcObj.has("faces") && srcObj.get("faces").isJsonObject()) {
                        JsonObject srcFaces = srcObj.getAsJsonObject("faces");
                        JsonObject outFaces = new JsonObject();

                        for (String faceName : new String[]{"north", "east", "south", "west", "up", "down"}) {
                            if (srcFaces.has(faceName)) {
                                JsonObject srcFace = srcFaces.getAsJsonObject(faceName);
                                JsonObject outFace = new JsonObject();
                                if (srcFace.has("uv")) outFace.add("uv", srcFace.get("uv"));
                                outFace.addProperty("texture", "#0");
                                if (srcFace.has("rotation")) outFace.addProperty("rotation", srcFace.get("rotation").getAsInt());
                                outFaces.add(faceName, outFace);
                            }
                        }
                        outObj.add("faces", outFaces);
                    }

                    outElements.add(outObj);
                }
                mcModel.add("elements", outElements);
            }

            // Display settings
            if (root.has("display") && root.get("display").isJsonObject()) {
                mcModel.add("display", root.getAsJsonObject("display"));
            } else {
                JsonObject display = new JsonObject();

                JsonObject thirdperson = new JsonObject();
                JsonArray rot = new JsonArray(); rot.add(75); rot.add(45); rot.add(0);
                JsonArray trans = new JsonArray(); trans.add(0); trans.add(2.5); trans.add(0);
                JsonArray scale = new JsonArray(); scale.add(0.375); scale.add(0.375); scale.add(0.375);
                thirdperson.add("rotation", rot);
                thirdperson.add("translation", trans);
                thirdperson.add("scale", scale);
                display.add("thirdperson_righthand", thirdperson);
                display.add("thirdperson_lefthand", thirdperson);

                JsonObject head = new JsonObject();
                JsonArray headScale = new JsonArray(); headScale.add(1.0); headScale.add(1.0); headScale.add(1.0);
                head.add("scale", headScale);
                display.add("head", head);

                JsonObject gui = new JsonObject();
                JsonArray guiRot = new JsonArray(); guiRot.add(30); guiRot.add(225); guiRot.add(0);
                JsonArray guiScale = new JsonArray(); guiScale.add(0.625); guiScale.add(0.625); guiScale.add(0.625);
                gui.add("rotation", guiRot);
                gui.add("scale", guiScale);
                display.add("gui", gui);

                mcModel.add("display", display);
            }

            String outputJson = GSON.toJson(mcModel);
            return new ConversionResult(outputJson, extractedTexture, textureFileName);
        }
    }
}
