package CustomContent.Pack;

import com.google.gson.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

/**
 * Parser konwertujący modele Blockbench (.bbmodel) do formatu Minecraft Java (.json)
 * z automatycznym skalowaniem współrzędnych UV do zakresu 0..16, ochroną limitu [-16.0, 32.0]
 * oraz ekstrakcją wszystkich zagnieżdżonych tekstur.
 */
public class BbmodelParser {

    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    public static class TextureData {
        public String id;
        public String fileName;
        public byte[] bytes;
        public double width;
        public double height;

        public TextureData(String id, String fileName, byte[] bytes, double width, double height) {
            this.id = id;
            this.fileName = fileName;
            this.bytes = bytes;
            this.width = width > 0 ? width : 16.0;
            this.height = height > 0 ? height : 16.0;
        }
    }

    public static class ConversionResult {
        public String modelJson;
        public List<TextureData> textures = new ArrayList<>();

        public ConversionResult(String modelJson, List<TextureData> textures) {
            this.modelJson = modelJson;
            this.textures = textures;
        }
    }

    /**
     * Konwertuje plik .bbmodel do formatu modelu Minecraft JSON oraz ekstrahuje wszystkie tekstury PNG.
     */
    public static ConversionResult convertBbmodel(File bbmodelFile, String textureNamespaceBase) throws Exception {
        try (Reader reader = new InputStreamReader(new FileInputStream(bbmodelFile), StandardCharsets.UTF_8)) {
            JsonObject root = JsonParser.parseReader(reader).getAsJsonObject();

            List<TextureData> extractedTextures = new ArrayList<>();
            Map<String, TextureData> textureMap = new HashMap<>();

            // 1. Ekstrakcja wszystkich tekstur z .bbmodel
            if (root.has("textures") && root.get("textures").isJsonArray()) {
                JsonArray textures = root.getAsJsonArray("textures");
                for (int i = 0; i < textures.size(); i++) {
                    JsonObject texObj = textures.get(i).getAsJsonObject();
                    String id = texObj.has("id") ? texObj.get("id").getAsString() : String.valueOf(i);
                    String name = texObj.has("name") ? texObj.get("name").getAsString() : "texture_" + id + ".png";
                    if (!name.endsWith(".png")) {
                        name += ".png";
                    }

                    double w = texObj.has("uv_width") ? texObj.get("uv_width").getAsDouble() : (texObj.has("width") ? texObj.get("width").getAsDouble() : 16.0);
                    double h = texObj.has("uv_height") ? texObj.get("uv_height").getAsDouble() : (texObj.has("height") ? texObj.get("height").getAsDouble() : 16.0);

                    byte[] bytes = null;
                    if (texObj.has("source") && !texObj.get("source").isJsonNull()) {
                        String source = texObj.get("source").getAsString();
                        if (source.contains("base64,")) {
                            String base64 = source.substring(source.indexOf("base64,") + 7);
                            bytes = Base64.getDecoder().decode(base64);
                        }
                    }

                    TextureData td = new TextureData(id, name, bytes, w, h);
                    extractedTextures.add(td);
                    textureMap.put(id, td);
                }
            }

            // 2. Budowa wynikowego modelu Minecraft JSON
            JsonObject mcModel = new JsonObject();
            mcModel.addProperty("credit", "Generated by AmonPack Model Engine");

            // Textures dictionary
            JsonObject texturesObj = new JsonObject();
            String baseTexKey = textureNamespaceBase;
            if (baseTexKey.endsWith(".png")) {
                baseTexKey = baseTexKey.substring(0, baseTexKey.length() - 4);
            }

            if (extractedTextures.isEmpty()) {
                texturesObj.addProperty("0", baseTexKey);
                texturesObj.addProperty("particle", baseTexKey);
            } else {
                for (TextureData td : extractedTextures) {
                    String subTexKey = baseTexKey;
                    if (extractedTextures.size() > 1 && !td.id.equals("0")) {
                        subTexKey = baseTexKey + "_" + td.id;
                    }
                    texturesObj.addProperty(td.id, subTexKey);
                }
                texturesObj.addProperty("particle", baseTexKey);
            }
            mcModel.add("textures", texturesObj);

            // Obliczenie granic modelu dla ochrony limitu [-16.0, 32.0] w Minecraft Java
            double maxY = -999;
            double minY = 999;
            if (root.has("elements") && root.get("elements").isJsonArray()) {
                JsonArray srcElements = root.getAsJsonArray("elements");
                for (JsonElement el : srcElements) {
                    if (!el.isJsonObject()) continue;
                    JsonObject srcObj = el.getAsJsonObject();
                    if (srcObj.has("from") && srcObj.has("to")) {
                        double fY = srcObj.getAsJsonArray("from").get(1).getAsDouble();
                        double tY = srcObj.getAsJsonArray("to").get(1).getAsDouble();
                        minY = Math.min(minY, Math.min(fY, tY));
                        maxY = Math.max(maxY, Math.max(fY, tY));
                    }
                }
            }

            double shiftY = 0.0;
            if (maxY > 32.0) {
                shiftY = -(maxY - 32.0);
            }

            // Elements
            if (root.has("elements") && root.get("elements").isJsonArray()) {
                JsonArray srcElements = root.getAsJsonArray("elements");
                JsonArray outElements = new JsonArray();

                for (JsonElement el : srcElements) {
                    if (!el.isJsonObject()) continue;
                    JsonObject srcObj = el.getAsJsonObject();

                    JsonObject outObj = new JsonObject();
                    if (srcObj.has("name")) outObj.addProperty("name", srcObj.get("name").getAsString());

                    // From i To z przesunięciem Y jeśli wymagane
                    if (srcObj.has("from") && srcObj.get("from").isJsonArray()) {
                        JsonArray f = srcObj.getAsJsonArray("from");
                        JsonArray newF = new JsonArray();
                        newF.add(clampCoord(f.get(0).getAsDouble()));
                        newF.add(clampCoord(f.get(1).getAsDouble() + shiftY));
                        newF.add(clampCoord(f.get(2).getAsDouble()));
                        outObj.add("from", newF);
                    }
                    if (srcObj.has("to") && srcObj.get("to").isJsonArray()) {
                        JsonArray t = srcObj.getAsJsonArray("to");
                        JsonArray newT = new JsonArray();
                        newT.add(clampCoord(t.get(0).getAsDouble()));
                        newT.add(clampCoord(t.get(1).getAsDouble() + shiftY));
                        newT.add(clampCoord(t.get(2).getAsDouble()));
                        outObj.add("to", newT);
                    }

                    // Rotation
                    if (srcObj.has("rotation") || srcObj.has("origin")) {
                        JsonObject rotObj = new JsonObject();
                        if (srcObj.has("origin") && srcObj.get("origin").isJsonArray()) {
                            JsonArray orig = srcObj.getAsJsonArray("origin");
                            JsonArray newOrig = new JsonArray();
                            newOrig.add(clampCoord(orig.get(0).getAsDouble()));
                            newOrig.add(clampCoord(orig.get(1).getAsDouble() + shiftY));
                            newOrig.add(clampCoord(orig.get(2).getAsDouble()));
                            rotObj.add("origin", newOrig);
                        }
                        if (srcObj.has("rotation") && srcObj.get("rotation").isJsonArray()) {
                            JsonArray rot = srcObj.getAsJsonArray("rotation");
                            if (rot.size() >= 3) {
                                double rx = rot.get(0).getAsDouble();
                                double ry = rot.get(1).getAsDouble();
                                double rz = rot.get(2).getAsDouble();
                                if (rx != 0) {
                                    rotObj.addProperty("axis", "x");
                                    rotObj.addProperty("angle", rx);
                                } else if (ry != 0) {
                                    rotObj.addProperty("axis", "y");
                                    rotObj.addProperty("angle", ry);
                                } else if (rz != 0) {
                                    rotObj.addProperty("axis", "z");
                                    rotObj.addProperty("angle", rz);
                                }
                            }
                        }
                        if (rotObj.has("axis")) {
                            outObj.add("rotation", rotObj);
                        }
                    }

                    // Faces
                    if (srcObj.has("faces") && srcObj.get("faces").isJsonObject()) {
                        JsonObject srcFaces = srcObj.getAsJsonObject("faces");
                        JsonObject outFaces = new JsonObject();

                        for (String faceName : new String[]{"north", "east", "south", "west", "up", "down"}) {
                            if (srcFaces.has(faceName)) {
                                JsonObject srcFace = srcFaces.getAsJsonObject(faceName);
                                JsonObject outFace = new JsonObject();

                                String texId = "0";
                                if (srcFace.has("texture") && !srcFace.get("texture").isJsonNull()) {
                                    texId = srcFace.get("texture").getAsString();
                                    if (texId.startsWith("#")) texId = texId.substring(1);
                                }
                                outFace.addProperty("texture", "#" + texId);

                                // Skalowanie UV do zakresu 0..16
                                if (srcFace.has("uv") && srcFace.get("uv").isJsonArray()) {
                                    JsonArray rawUv = srcFace.getAsJsonArray("uv");
                                    if (rawUv.size() == 4) {
                                        TextureData td = textureMap.get(texId);
                                        double tw = (td != null && td.width > 0) ? td.width : 16.0;
                                        double th = (td != null && td.height > 0) ? td.height : 16.0;

                                        double u1 = (rawUv.get(0).getAsDouble() / tw) * 16.0;
                                        double v1 = (rawUv.get(1).getAsDouble() / th) * 16.0;
                                        double u2 = (rawUv.get(2).getAsDouble() / tw) * 16.0;
                                        double v2 = (rawUv.get(3).getAsDouble() / th) * 16.0;

                                        JsonArray scaledUv = new JsonArray();
                                        scaledUv.add(Math.round(u1 * 1000.0) / 1000.0);
                                        scaledUv.add(Math.round(v1 * 1000.0) / 1000.0);
                                        scaledUv.add(Math.round(u2 * 1000.0) / 1000.0);
                                        scaledUv.add(Math.round(v2 * 1000.0) / 1000.0);
                                        outFace.add("uv", scaledUv);
                                    }
                                }

                                if (srcFace.has("rotation")) outFace.addProperty("rotation", srcFace.get("rotation").getAsInt());
                                outFaces.add(faceName, outFace);
                            }
                        }
                        outObj.add("faces", outFaces);
                    }

                    outElements.add(outObj);
                }
                mcModel.add("elements", outElements);
            }

            // Display settings
            if (root.has("display") && root.get("display").isJsonObject()) {
                mcModel.add("display", root.getAsJsonObject("display"));
            } else {
                JsonObject display = new JsonObject();

                JsonObject thirdperson = new JsonObject();
                JsonArray rot = new JsonArray(); rot.add(75); rot.add(45); rot.add(0);
                JsonArray trans = new JsonArray(); trans.add(0); trans.add(2.5); trans.add(0);
                JsonArray scale = new JsonArray(); scale.add(0.375); scale.add(0.375); scale.add(0.375);
                thirdperson.add("rotation", rot);
                thirdperson.add("translation", trans);
                thirdperson.add("scale", scale);
                display.add("thirdperson_righthand", thirdperson);
                display.add("thirdperson_lefthand", thirdperson);

                JsonObject head = new JsonObject();
                JsonArray headScale = new JsonArray(); headScale.add(1.0); headScale.add(1.0); headScale.add(1.0);
                head.add("scale", headScale);
                display.add("head", head);

                JsonObject gui = new JsonObject();
                JsonArray guiRot = new JsonArray(); guiRot.add(30); guiRot.add(225); guiRot.add(0);
                JsonArray guiScale = new JsonArray(); guiScale.add(0.625); guiScale.add(0.625); guiScale.add(0.625);
                gui.add("rotation", guiRot);
                gui.add("scale", guiScale);
                display.add("gui", gui);

                JsonObject fixed = new JsonObject();
                JsonArray fixedScale = new JsonArray(); fixedScale.add(1.0); fixedScale.add(1.0); fixedScale.add(1.0);
                fixed.add("scale", fixedScale);
                display.add("fixed", fixed);

                mcModel.add("display", display);
            }

            String outputJson = GSON.toJson(mcModel);
            return new ConversionResult(outputJson, extractedTextures);
        }
    }

    private static double clampCoord(double val) {
        if (val < -16.0) return -16.0;
        if (val > 32.0) return 32.0;
        return Math.round(val * 1000.0) / 1000.0;
    }
}
