Bosses:
  Zombie_Raider:
    MythicMobName: "Zombie_Raider"
    DisplayName: "&4Najeźdzca zza grobu"
    Type: "SINGLE"
    LootTable:
      - Material: "DIAMOND"
        Amount: 1
        Chance: 0.5
      - Material: "IRON_INGOT"
        Amount: 8
        Chance: 1.0
      - Material: "ROTTEN_FLESH"
        Amount: 10
        Chance: 1.0
      - Material: "BONE"
        Amount: 8
        Chance: 1.0
  Pirates:
    MythicMobName: "Pirate_1_Sniper"
    DisplayName: "&aPirat - Snajper"
    Type: "SINGLE"
    GroupSize: 1
    LootTable:
      - Material: "COPPER_INGOT"
        Amount: 6
        Chance: 1.0
      - Material: "FEATHER"
        Amount: 4
        Chance: 0.8
      - Material: "ARROW"
        Amount: 8
        Chance: 1.0
  TestBoss:
    MythicMobName: "Zombie_Raider"
    DisplayName: "&4Najeźdzca zza grobu"
    Type: "SINGLE"
    LootTable:
      - Material: "DIAMOND"
        Amount: 2
        Chance: 1.0
      - Material: "GOLD_INGOT"
        Amount: 5
        Chance: 0.5
      - Material: "NETHER_STAR"
        Amount: 1
        Chance: 0.1
  TestGroup:
    MythicMobName: "Pirate_1_Sniper"
    DisplayName: "&aPirat - Snajper"
    Type: "GROUP"
    GroupSize: 1
    LootTable:
      - Material: "IRON_INGOT"
        Amount: 10
        Chance: 1.0
      - Material: "BONE"
        Amount: 20
        Chance: 0.8
