name: AmonPack
version: '1.0-SNAPSHOT'
main: methods_plugins.AmonPackPlugin
api-version: 1.20
authors: [ Amon ]
depend: ['ProjectKorra']
description: 'Plugin made for Avatarserv'
commands:
  QuestItems:
    description: QuestItems
    usage: /<command>
  Puzzle:
    usage: /<command>
  ArenaBuilding:
    usage: /<command>
  Menagerie:
    usage: /<command>
  PvP:
    usage: /<command>
  Level:
    usage: /<command>
  Reload:
    usage: /<command>