name: AmonPack
version: '1.1'
main: methods_plugins.AmonPackPlugin
api-version: 1.20
authors: [ Amon ]
depend: ['ProjectKorra']
description: 'Plugin made for Avatarserv'
commands:
  Puzzle:
    usage: /<command>
  ArenaBuilding:
    usage: /<command>
  Menagerie:
    usage: /<command>
  Level:
    usage: /<command>
  Reload:
    usage: /<command>
  Craft:
    usage: /<command>