name: AmonPack
version: '${project.version}'
main: methods_plugins.AmonPackPlugin
api-version: 1.18
authors: [ Amon ]
depend: ['ProjectKorra']
description: 'Plugin made for Avatarserv'
commands:
  QuestItems:
    description: QuestItems
    usage: /<command>
  Skills:
    description: choose yours spells
    usage: /<command>
  Puzzle:
    usage: /<command>
  MinGathOff:
    usage: /<command>
  MinGathOn:
    usage: /<command>
  Pomoc:
    usage: /<command>
  ArenaBuilding:
    usage: /<command>
  Menagerie:
    usage: /<command>
  SpellTree:
    usage: /<command>
  PvP:
    usage: /<command>
  Level:
    usage: /<command>
  Reload:
    usage: /<command>