name: AmonPack
version: '${project.version}'
main: Plugin.AmonPackPlugin
api-version: 1.20
authors: [ Amon ]
depend: ['ProjectKorra']
softdepend: [WorldEdit, FastAsyncWorldEdit]
description: 'Plugin made for Avatarserv'
commands:
  Reload:
    usage: /<command>
    description: "Reloads AmonPack plugin configuration"